# Generated by Django 3.2 on 2021-05-11 05:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', ckeditor.fields.RichTextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
