# Generated by Django 3.2 on 2021-05-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_main_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_description',
            new_name='description',
        ),
    ]
